info:
  component: Hystrix Dashboard
  
server:
  port: ${port:8511}


eureka:
    # Region where eureka is deployed - For AWS specify one of the AWS regions, for other datacenters specify a arbitrary string
    # indicating the region.This is normally specified as a -D option (eg) -Deureka.region=us-east-1
    #region: default
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  # support to resolve service-id 
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOSTNAME:localhost}:8761/eureka/

logging:
  level:
    ROOT: INFO
    org.chiwooplatform.cloud.sample: DEBUG